### ISSUE TITLE
Unexpected key(s) in state_dict: "embeddings.position_ids"

### ISSUE THREAD

**Issue by ZwormZ** [chao1224/MoleculeSTM#10]
Hello, I have downloaded the toy checkpoint that you provided. 
However, when I try to run the script "downstream_01_retrieval_ATC_Retrieval.py", I have noticed that the text model dict does not match with "scibert_scivocab_uncased". Is the text model slightly different from Scibert?

![image](https://github.com/chao1224/MoleculeSTM/assets/52192467/a47977aa-9108-4091-8d6c-7b9cd225c8b8)

**Comment by chao1224** [comment]
Hi @ZwormZ , that's interesting. I haven't seen this before, and I'm pretty sure that we haven't changed the scibert model. Can you give the exact CMD and complete screenshot?

**Comment by ZwormZ** [comment]
I have printed the Scibert module layer and the MoleculeSTM's text_model name and discovered that the text_model has an additional layer called "embedding.position_ids".
![image](https://github.com/chao1224/MoleculeSTM/assets/52192467/f2a414f1-733a-4a2f-9721-a5f24cb617d6)

**Comment by ZwormZ** [comment]
Hi，I have printed the Scibert module layer and the MoleculeSTM's text_model name and discovered that the text_model has an additional layer called "embedding.position_ids".
![image](https://github.com/chao1224/MoleculeSTM/assets/52192467/a8ef6b22-4cb8-460e-8a96-896468bf2199)

And this is the script

![image](https://github.com/chao1224/MoleculeSTM/assets/52192467/eed81db9-226d-46e1-92bf-74d3a60e8770)

**Comment by chao1224** [comment]
Hi @ZwormZ,

I just tried this, and everything works well on my end. I suspect that this might be the HF version issue.
BTW. I am using the following:
```
transformers          4.26.1
```

**Comment by Youzhuqinghuan** [comment]
https://github.com/flairNLP/flair/issues/3284 Here I find the same problem.
Use ` text_model.load_state_dict(state_dict, strict=False)` can ignore it.:)
