### ISSUE TITLE
Processing ".cif" file.

### ISSUE THREAD

**Issue by Sharpiless** [chao1224/MoleculeSTM#17]
Hi, great work! I wonder if it is possible to input a ".cif" file containing the molecular structure and extract its latent features?

**Comment by chao1224** [comment]
Hi @Sharpiless,

Thank you for your interest!

By the `.cif` file, I assume you refer to the 3D geometry. If so, then the current version of MoleculeSTM does not support it. However, you can replace the 2D molecule encoder (GIN) or 1D molecule encoder (MegaMolBART encoder) with the 3D encoder (we have another work [Geom3D](https://github.com/chao1224/Geom3D) that can be easily adopted here).
