### ISSUE TITLE
Missing downsload_MegaBolBART.sh

### ISSUE THREAD

**Issue by ZwormZ** [chao1224/MoleculeSTM#2]
Hello, thank you for sharing this fantastic work.

I noticed that during the pretraining stage, as outlined in the paper, the SMILES encoder uses MegaMolBART's encoder. However, I could not find the downsload_MegaBolBART.sh file in this repository. Additionally, I checked the paper you cited in MoleculesSTM, which is "Chemformer: a pre-trained transformer for computational chemistry," but it seems that they did not provide the model checkpoint.

Could you please advise me on how I can obtain the pretrained checkpoint for the SMILES encoder that uses MegaMolBART's encoder?

**Comment by chao1224** [comment]
Hi @ZwormZ,

You may now refer to [this script](https://github.com/NVlabs/RetMol/blob/main/download_scripts/download_models.sh). There are five folders after unzipping, and `megamolbart` is the one we used here.

(I am checking how to add the scripts to this repo.)

**Comment by ZwormZ** [comment]
Great! I downloaded this checkpoint using the script you provided and it worked. Thank you!

**Comment by chao1224** [comment]
Glad it helps.
