### ISSUE TITLE
wget returns empty zip dictionary for MegaMolBART checkpoints

### ISSUE THREAD

**Issue by cankobanz** [chao1224/MoleculeSTM#20]
Hi,
I am trying to get pretrained MegaMolBART files as you described in [here.](https://github.com/chao1224/MoleculeSTM/blob/main/README.md#32-megamolbart)

However, something is not working after wget command:
https://github.com/chao1224/MoleculeSTM/blob/64d75c9b46da4552e370cdcaea69f5f259108a0f/download_MegaMolBART.sh#L5

Because, it returns empty zip file. Here, the what I get after wget command:

> --2024-01-31 08:35:52--  https://docs.google.com/uc?export=download&confirm=&id=1O5u8b_n93HOrsjN1aezq6NhZojh-6dEe
> Resolving docs.google.com (docs.google.com)... 74.125.132.139, 74.125.132.100, 74.125.132.138, ...
> Connecting to docs.google.com (docs.google.com)|74.125.132.139|:443... connected.
> HTTP request sent, awaiting response... 303 See Other
> Location: https://drive.usercontent.google.com/download?id=1O5u8b_n93HOrsjN1aezq6NhZojh-6dEe&export=download [following]
> --2024-01-31 08:35:52--  https://drive.usercontent.google.com/download?id=1O5u8b_n93HOrsjN1aezq6NhZojh-6dEe&export=download
> Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 64.233.182.132, 2607:f8b0:4001:c0a::84
> Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|64.233.182.132|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 2422 (2.4K) [text/html]
> Saving to: ‘models.zip’
> 
> models.zip          100%[===================>]   2.37K  --.-KB/s    in 0s      
> 
> 2024-01-31 08:35:52 (48.1 MB/s) - ‘models.zip’ saved [2422/2422]

Can you help me with this please?

**Comment by chao1224** [comment]
Hi @cankobanz,

This script follows [this link](https://github.com/NVlabs/RetMol/blob/main/download_scripts/download_models.sh), but the script seems not working now. I will push a version from my end.

**Comment by cankobanz** [comment]
@chao1224 Hello, thank you for your support. Please let me know when the latest version is available.

**Comment by chao1224** [comment]
Hi @cankobanz,

Server has been down for days. Will keep you updated once it's back.

**Comment by chao1224** [comment]
Hi @cankobanz,

Sorry for keeping you waiting. This [link](https://drive.google.com/file/d/1fz4fls8gcvq8XmEau_iw-V7Jsdg1C2ZO/view?usp=sharing) should work.
