### ISSUE TITLE
How can I reproduce the results of the Graph modality in the structure-text retrieval experiment?

### ISSUE THREAD

**Issue by chenjinyu0723** [chao1224/MoleculeSTM#27]
Hello, I am a senior student and I am new in the field of deep learning.
For zero-shot structure-text retrieval, I have basically reproduced the results for the SMILES modality correctly.  
This is the result I get using the DrugBank Description(given structure) for the SMILES modality. This might be slight deviations, but it's essentially correct.
<img width="260" alt="1-given_structure-Description-SMILES" src="https://github.com/chao1224/MoleculeSTM/assets/118201974/720d7250-6b32-4b58-80ec-e84fce7c9d4f">
However, the results I get from the Graph modality on the same dataset vary significantly. 
<img width="455" alt="1718602109227" src="https://github.com/chao1224/MoleculeSTM/assets/118201974/70709e60-2274-4dd8-bca5-8ca6f9d4b80e">
I followed the instructions in README.md and ran the code step by step. I replaced the experiment's checkpoint with the one mentioned in scripts/README.md, such as using this code:

   python downstream_01_retrieval_Description_Pharmacodynamics.py \
    --task=molecule_description_removed_PubChem \
    --molecule_type=Graph \
    --input_model_dir=../data/pretrained_MoleculeSTM/SciBERT-Graph-3e-5-1-1e-4-1-InfoNCE-0.1-32-32

I would greatly appreciate it if you could respond whenever you have time to let me know where the issue might be. Looking forward to your reply.

Also, I would like to ask what the ‘seed’ are set for all the three experiments?

**Comment by chao1224** [comment]
Hi @chenjinyu0723 , this is related to #16. You can check the details (e.g., seed) there.
