### ISSUE TITLE
Molecular Property Prediction giving `train: 0.000000` in every epoch

### ISSUE THREAD

**Issue by MohdOwais22** [chao1224/MoleculeSTM#28]
![Screenshot from 2024-07-04 12-21-48](https://github.com/chao1224/MoleculeSTM/assets/78542017/483e44de-d70b-49c3-a650-9a791ada8742)

i was running the script under 4.4 Downstream: Molecular Property Prediction and demo file of demo_downstream_property_prediction_SMILES.ipynb in demos folder both of them showing train 0.00 does that mean the checkpoints file is corrupted how can i fix the issue?

**Comment by chao1224** [comment]
Hi @MohdOwais22 , the `0.0000` here means we are not reporting the training metric. There is a [eval-train](https://github.com/chao1224/MoleculeSTM/blob/main/scripts/downstream_03_property_prediction.py#L233) hyperparameter controlling this.
