### ISSUE TITLE
implemention about clip_loss_for_edit() function

### ISSUE THREAD

**Issue by spoilvoid** [chao1224/MoleculeSTM#33]
In [molecular_edit](scripts/downstream_02_molecule_edit_step_02_MoleculeSTM_Latent_Optimization.py)，I think your clip_loss_for_edit(molecule_repr, text_repr) is wrong if batch_size > 1. I suppose you should choose similarity matrix‘s diagonal rather than 1st row.  
The code you release is below  
```
def clip_loss_for_edit(molecule_repr, text_repr):
    molecule_repr = F.normalize(molecule_repr, dim=-1)
    text_repr = F.normalize(text_repr, dim=-1)

    similarity = -torch.mm(molecule_repr, text_repr.transpose(0, 1))[0]
    return similarity
```

**Comment by chao1224** [comment]
Hi,

Please check [this function](https://github.com/chao1224/MoleculeSTM/blob/main/scripts/downstream_02_molecule_edit_step_02_MoleculeSTM_Latent_Optimization.py#L29), which calls the `clip_loss_for_edit`.

**Comment by spoilvoid** [comment]
I understand. You only use 1 smiles as input, so there's no difference between matrix‘s diagonal rather and 1st row.
