### ISSUE TITLE
4.3 Downstream: Zero-shot Text-based Molecule Editing 

### ISSUE THREAD

**Issue by cyz-32526** [chao1224/MoleculeSTM#5]
在使用指令python downstream_02_molecule_edit_step_01_MoleculeSTM_Space_Alignment.py \
    --MoleculeSTM_molecule_type=Graph \
    --MoleculeSTM_model_dir=../data/demo/demo_checkpoints_Graph
    运行MoleculeSTM-Graph编辑任务的时候出现了如下报错。

RuntimeError: Error(s) in loading state_dict for GNN_graphpred:
        size mismatch for molecule_node_model.atom_encoder.atom_embedding_list.1.weight: copying a param with shape torch.Size([4, 300]) from checkpoint, the shape in current model is torch.Size([5, 300]).
        请问这个该怎么解决啊~

**Comment by chao1224** [comment]
Hi @cyz-001, 你那里有更完整的报错信息么？

现在看起来报错的代码是[这一行](https://github.com/chao1224/MoleculeSTM/blob/main/MoleculeSTM/models/molecule_gnn_model.py#L78) layer定义和checkpoint的layer shape不一致。你的OGB版本是多少？

**Comment by cyz-32526** [comment]
谢谢你的回复！我降低了OGB版本到1.2，问题得到了解决。非常感谢你的建议！~
