### ISSUE TITLE
Toy Checkpoints for MoleculeSTM

### ISSUE THREAD

**Issue by Greay83** [chao1224/MoleculeSTM#6]
Hi, this is a very cool work, thanks for sharing this repository.
We found that the performance of the toy checkpoints provided by huggingface is much lower than the results in the paper, whether it is because it has not been trained enough epochs. Could you please provide the details of the hyperparameters of the toy checkpoints?
Thanks so much!

**Comment by chao1224** [comment]
Hi @Greay83,
The reason is that the hyperparameters in `toy checkpoint` are not optimal. We will release the optimal ones soon.

**Comment by Greay83** [comment]
Thanks a lot. I'm looking forward it!
