### ISSUE TITLE
file missing

### ISSUE THREAD

**Issue by Nireus-lgx** [chao1224/MoleculeSTM#7]
hi,
I'm very interested in your work, 
but in the process of reproducing it, I can't find this file: `downsload_MegaBolBART.sh`

**Comment by chao1224** [comment]
Hi @Nireus-lgx,

You can find it here #2.

**Comment by Nireus-lgx** [comment]
thanks!

**Comment by Nireus-lgx** [comment]
> Hi @Nireus-lgx,
> 
> You can find it here #2.

it worked ，thanks !
