### ISSUE TITLE
How do I get the latest "CID2SMILES.csv" data file

### ISSUE THREAD

**Issue by Greay83** [chao1224/MoleculeSTM#8]
Hi, this is a very cool work, thanks for sharing this repository.

The code on github does not generate the latest "CID2SMILES.csv" file, except for an earlier version uploaded on huggingface. How do I get the latest version of this file?

Thank you in advance :)

**Comment by chao1224** [comment]
Hi @Greay83,

You can obtain this by mapping the CID and SMILES using the downloaded and preprocessed files under this [folder](https://github.com/chao1224/MoleculeSTM/tree/main/preprocessing/PubChemSTM).

Yet, in case you need it, I just uploaded my local script to the main branch (same folder with the name `step_05`). Feel free to check.

**Comment by Greay83** [comment]
Thank you for your notice!
Sincerely.
