### ISSUE TITLE
How to solve this

### ISSUE THREAD

**Issue by yxliu0907** [chao1224/MoleculeSTM#9]

**Comment by yxliu0907** [comment]
![ce6444a3e39c516a32181022854710f](https://github.com/chao1224/MoleculeSTM/assets/153621298/a288c8a8-f6cd-46f6-a574-3c55845d1cdb)
This problem occurs when I execute pretrain.py with the default parameter.

**Comment by chao1224** [comment]
Hi @yxliu0907,
I suspect that this may be related to the package versions.
Can you help share the complete screenshot?

**Comment by chao1224** [comment]
Hi @yxliu0907,

I just tried the scripts, and everything works well on my end. Can you help elaborate more on your exceptions?

**Comment by yxliu0907** [comment]
Thanks for answering. I found the question. I was afraid that the quantities of smiles.csv and CID2text.json did not match, so I filtered the CIDD2text.json. However, each piece of filtered data has an extra "[ ]".
